- name: Install QoL packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: Remove useless Raspberry Pi packages
  apt:
    name: ['wolfram-engine', 'sonic-pi', 'scratch', 'nuscratch', 'penguinspuzzle']
    state: absent
    purge: true

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Add common bash aliases
  lineinfile:
    path: "~/.bash_aliases"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    create: yes
  with_items:
    - { regexp: "^#?alias ..=", line: "alias ..='cd ..'" }
    - { regexp: "^#?alias dco=", line: "alias dco='docker-compose'" }
    - { regexp: "^#?alias dcod=", line: "alias dcod='docker-compose down'" }
